# Generated by scripts/analyze_calibration.py
# tau = 3 x observed max |a-e|
# factor: smallest integer whose fitted false-positive probability stays <= 1e-12 at every size
declare -A TAU_TABLE=(
  [512]="0.000319"
  [1024]="0.000802"
  [2048]="0.002312"
  [4096]="0.021641"
  [8192]="0.059241"
  [10240]="0.088163"
)
